server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: 'routes'

spring:
  application:
    name: zuul-proxy

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://admin:pass@localhost:8761/eureka

zuul:
  ignoredServices: '*'
  routes:
    models-service:
      path: /api/**
      serviceId: models-service
      stripPrefix: true